name: Build and Export Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build -t my-docker-image:latest .

      - name: Export Docker Image
        run: |
          docker save my-docker-image:latest | gzip > my-docker-image-latest.tar.gz
          echo "::set-output name=docker-image::my-docker-image-latest.tar.gz"

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-docker-image
          path: my-docker-image-latest.tar.gz
